name: fit_book
description: Track your calories - Completely offline!
publish_to: none
version: 1.0.42+43
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.9.0
  provider: ^6.1.2
  dynamic_color: ^1.7.0
  file_picker: ^8.0.3
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0
  csv: ^6.0.0
  rxdart: ^0.27.7
  sqlite3: ^2.4.3
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2
  background_fetch: ^1.3.5
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_launcher_icons:
  android: false
  ios: true
  image_path: assets/ic_launcher.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/ic_launcher.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/ic_launcher.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/ic_launcher.png
