services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      USERNAME: bill
      PASSWORD: gates
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 42069:22
    volumes:
      - ./build/windows:/shared
    stop_grace_period: 2m
