allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.addAll(['-Xlint:-options'])
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    apply plugin: 'kotlin-android'

    plugins.withId('com.android.library') {
        if (project.name == 'jni') {
            android {
                defaultConfig {
                    externalNativeBuild {
                        cmake {
                            arguments '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--build-id=none'
                        }
                    }
                }
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
ext {
    compileSdkVersion = 36
    targetSdkVersion = 36
    appCompatVersion = "1.4.2"
}
