name: Shared Flutter quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality:
    uses: brandonp2412/Flexify/.github/workflows/flutter-quality.yml@9cbb2208242a39aa4da3db833bac422891eeb5da
